DHT/urls.py
from django.urls import path, include
from . import views
from . import api

app_name='DHT'

urlpatterns = [
    path("api",api.dhtser,name='json'),
    path('download_csv/', views.download_csv, name='download_csv'),
    path('', include('core.urls')),
    path('table/', views.table, name='table'),
    path('myChartTemp/',views.graphiqueTemp,name='myChart'),
    path('myChartHum/',views.graphiqueHum,name='myChart'),
    path ('chart-data/',views.chart_data, name='chart-data'),
    path('chart-data-jour/',views.chart_data_jour,name='chart-data-jour'),
    path('chart-data-semaine/',views.chart_data_semaine,name='chart-data-semaine'),
    path('chart-data-mois/',views.chart_data_mois,name='chart-data-mois'),
    path('new/', views.new , name='new'),





]

core/urls.py
from django.urls import path
from . import views
from .forms import LogInForm
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

app_name='core'

urlpatterns=[
    path('', views.index , name='index'),
    path('signup/', views.signup , name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LogInForm), name='login'),
    path('logout/', views.logout_user,name='logout'),
]

projet/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('DHT.urls')),
    path('core/', include('core.urls'))
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from DHT.models import Dht11


class LogInForm(AuthenticationForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
class SignUpForm(UserCreationForm):
    class Meta:
        model=User
        fields= ('username', 'email' , 'password1' , 'password2')

    username=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class' : 'w-full py-4 px-6 rounded-xl'
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your confirmation password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your confirmation password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

core/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.shortcuts import render, redirect
from .forms import SignUpForm

from django.http import HttpResponse
# Create your views here.


from django.contrib.auth import authenticate, login,logout


def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        # Authenticating the user
        user = authenticate(request, username=username, password=password)
        # Checking if authentication is successful
        if user is not None:
            login(request, user)
            return redirect("/")
        else:
            return render(request, 'login.html', {'error': 'Invalid credentials'})

    return render(request, 'login.html')


def logout_user(request):
    logout(request)
    return redirect('/')

def index(request):
    return render(request, 'core/index.html')

def signup(request):
    if request.method == 'POST':
        form=SignUpForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')

    else:
        form = SignUpForm()

    return render(request, 'core/signup.html', {'form' : form})

core/templates/core/base.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.tailwindcss.com"></script>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.css"  rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.js"></script>
        <script src="https://kit.fontawesome.com/2849d571f5.js" crossorigin="anonymous"></script>
        <title>{% block title %} {% endblock %} | Project IOT</title>
    </head>
    <body class="bg-white">
        <nav class="px-6 py-6 flex justify-between bg-cyan-200 items-center border-b border-gray-200">
                <a href="/" class="text-xl text-blue-600 font-semibold">Project IOT</a>

                <div class="space-x-6">

                    <a href="/table/" class="text-blue-600 text-base font-semibold hover:text-gray-500">Index</a>
                    <a href="/new/" class="text-blue-600 text-base font-semibold hover:text-gray-500">New Measure</a>

                    <button id="dropdownDefaultButton" data-dropdown-toggle="dropdown" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" type="button">My charts <svg class="w-2.5 h-2.5 ms-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
                        </svg>
                    </button>

                    <!-- Dropdown menu -->
                    <div id="dropdown" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
                        <ul class="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownDefaultButton">
                            <li>
                                <a href="/myChartTemp/" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Temperature</a>
                            </li>
                            <li>
                                <a href="/myChartHum/" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Humidity</a>
                            </li>
                        </ul>
                    </div>


                    {% if request.user.is_authenticated %}
                    <!-- <a href="#" class="px-6 py-3 text-base font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-600">Inbox</a>
                    <a href="" class="px-6 py-3 text-base font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
                    -->
                    <a href="{% url 'core:logout' %}" class="px-6 py-3 text-base font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Logout</a>
                    {% else %}
                    <a href="{% url 'core:signup' %}" class="px-6 py-3 text-base font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-600">Sign up</a>
                    <a href="{% url 'core:login' %}" class="px-6 py-3 text-base font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
                    {% endif %}
                </div>
        </nav>

        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="py-3 px-4 flex justify-between bg-gray-800">
            <div class="w-3/4 pr-10">
                <h3 class="mb-2 font-semibold text-gray-400">About</h3>

                <p class="text-lg text-gray-500">Projet IOT au compte de la 5ème année Génie Informatique à l'Ecole des Hautes Etudes d'Ingénieurie. </p>
            </div>
            <div class="ml-8 w-1/4">
                <h3 class="mb-1 font-semibold text-gray-400">Menu</h3>
                <ul class="space-y-1">
                    <li><a href="" class="text-base text-teal-500 hover:text-teal-700">About</a> </li>
                    <li><a href="#" class="text-base text-teal-500 hover:text-teal-700">Privacy policy</a> </li>
                </ul>
            </div>
        </footer>
    </body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static  %}
{% block title %} Welcome {% endblock %}

{% block content %}

<div class="font-bold text-center mb-2 text-2xl">Projet Internet of Objects 5ème année Génie Informatique EHEI</div>
<div class="flex flex-row">
  <div class="w-2/5 mt-6 mr-8">
    <img class="border-dotted border-2 border-indigo-600 rounded-lg shadow-2xl" src="{% static 'core/images/DHT11.png' %}">
  </div>
  <div class=" w-3/5">
      <div>
          <h1 class="font-bold text-center mt-5 mb-3 text-blue-600 text-xl">Introduction sur le DHT11 : <i class="px-3 fa-solid fa-temperature-high"></i></h1>
          <p class="font-normal text-neutral-950"><span class="font-bold text-blue-600">Le capteur DHT11 </span> est un capteur de <span class="font-bold text-red-600">température</span> et d'<span class="font-bold text-red-400">humidité</span>. Il permet la mesure de ces grandeurs physiques avec précision. Il est souvent vendu sur une carte support qui possède <span class="font-bold text-lime-600">3 broches.</span> Il communique avec l’<span class="font-bold text-blue-600">Arduino</span> très simplement au travers d’une de ses entrées numériques.
    La broche principale est celle qui fournit les <span class="font-bold text-blue-600">DATA</span>. Les 2 autres broches sont pour son alimentation <span class="font-bold text-blue-600">5V</span> et la masse <span class="font-bold text-blue-600">GND</span>. <br>
              Le module <span class="font-bold text-blue-600">DHT11</span> est facile à utiliser avec les cartes <span class="font-bold text-blue-600">Arduino</span>, <span class="font-bold text-indigo-600">Raspberry,</span> <span class="font-bold text-indigo-600">Pi</span> et <span class="font-bold text-indigo-600">Nodemcu</span>. Au niveau logiciel, il existe des bibliothèques pour Arduino avec prise en charge du protocole <span class="font-bold">“Single bus”.</span> <br>
       En ce qui concerne le matériel, il suffit de connecter la broche d’alimentation VCC à 3 ou 5V, la broche GND à la masse (0V) et la broche de données à une broche numérique.</p>
          <h1 class="font-bold text-center mt-5 mb-3 text-blue-600 text-xl">Spécifications et caractéristiques: <i class="px-3 fa-solid fa-list"></i></h1>



         <ul class="list-disc px-4">
            <li>Tension de fonctionnement : 3,5 V à 5,5 V</li>
             <li>Plage de mesure de l’humidité : 20 % à 90 % HR (erreur de mesure de l’humidité : +-5 %)</li>
             <li>Résolution de mesure de l’humidité : 1 % HR/li>
             <li>Tension de fonctionnement : 3,5 V à 5,5 V</li>
             <li>Erreur de mesure de température : +-2°</li>
             <li>Résolution de mesure de température : 1 ºC</li>
             <li>Portée de transmission du signal : 20 mètres</li>
             <li>Dimensions : 19 mm x 17 mm x 19 mm</li>
             <li>Poids : 3g</li>
        </ul>
         </div>
</div>
  </div>
<div class=" flex flex-center flex-col">


</div>


{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %} Log in {% endblock %}

 {% block content %}
<div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl border-solid border-2 border-amber-300">
    <h1 class="mb-4 text-3xl p-6">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}



        <div class="mb-3">
            <label class="inline-block mb-2">Username :</label><br>
            {{ form.username }}
        </div>



        <div class="mb-3">
            <label class="inline-block mb-2">Password :</label><br>
            {{ form.password }}
        </div>



        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="ml-4 mt-4 py-4 px-8 text-sm bg-cyan-300 hover:bg-teal-700 rounded-xl">Log in</button>
    </form>
</div>


{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %} Sign up {% endblock %}

{% block content %}
<div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl border-solid border-2 border-amber-300">
    <h1 class="mb-5 text-3xl p-6">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}



        <div class="mb-3">
            <label class="inline-block mb-2">Username :</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email :</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password :</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Confirm Password :</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
            </div>
        {% endif %}
        <button class=" ml-4 mt-4 py-4 px-8 text-sm bg-cyan-300 hover:bg-teal-700 rounded-xl">Submit</button>
    </form>
</div>
{% endblock %}